[package]
name = "xrpals-lps-server"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
futures = "0.3.31"
bytes = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
